name: Helm Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_EKS }}

      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION_EKS }} --name kafka-microservices

      - name: Verify cluster access
        run: kubectl get nodes

      - uses: actions/checkout@v4
      - name: Helm upgrade
        run: |
          helm upgrade --install producer1 ./charts --namespace default

