name: Helm Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm upgrade
        run: |
          helm upgrade --install producer1 ./charts --namespace default

